// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHMiPwRRU8Stjt-4PfCV1dKjyDWfB_4mI',
    appId: '1:278570672738:web:2325abf0f4f827f525e73b',
    messagingSenderId: '278570672738',
    projectId: 'unfat-app-2f678',
    authDomain: 'unfat-app-2f678.firebaseapp.com',
    storageBucket: 'unfat-app-2f678.firebasestorage.app',
    measurementId: 'G-TEQ94LMKRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZclQrdGtknu4fUCloyWBIul0ZJeyTNTQ',
    appId: '1:278570672738:android:d381fdf3b8a2832725e73b',
    messagingSenderId: '278570672738',
    projectId: 'unfat-app-2f678',
    storageBucket: 'unfat-app-2f678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5FqxdjWBHWO32v1QPEy54njCPwyC4P2Y',
    appId: '1:278570672738:ios:faeb867a6275f38725e73b',
    messagingSenderId: '278570672738',
    projectId: 'unfat-app-2f678',
    storageBucket: 'unfat-app-2f678.firebasestorage.app',
    iosBundleId: 'com.example.unfat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5FqxdjWBHWO32v1QPEy54njCPwyC4P2Y',
    appId: '1:278570672738:ios:faeb867a6275f38725e73b',
    messagingSenderId: '278570672738',
    projectId: 'unfat-app-2f678',
    storageBucket: 'unfat-app-2f678.firebasestorage.app',
    iosBundleId: 'com.example.unfat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHMiPwRRU8Stjt-4PfCV1dKjyDWfB_4mI',
    appId: '1:278570672738:web:1a9cc6e3e52e0f1c25e73b',
    messagingSenderId: '278570672738',
    projectId: 'unfat-app-2f678',
    authDomain: 'unfat-app-2f678.firebaseapp.com',
    storageBucket: 'unfat-app-2f678.firebasestorage.app',
    measurementId: 'G-GT81KM4F8T',
  );

}